services:
   fan-video:
      build: .
      image: mobufan/fan-video:latest
      container_name: fan-video
      ports:
         - 8060:8080
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Asia/Shanghai
      volumes:
         - ./data:/data
         - ./cache:/cache
         - /vol2/1000/mydisk/Video:/media:ro
      devices:
         - /dev/dri:/dev/dri
      deploy:
         resources:
            limits:
               cpus: "4"
               memory: 4G
      restart: unless-stopped
