package main

import (
	"github.com/fan-video/fan-video/internal/config"
	"github.com/fan-video/fan-video/internal/handler"
	"github.com/fan-video/fan-video/internal/middleware"
	"github.com/gin-gonic/gin"
)

func registerAdminAPI(r *gin.Engine, cfg *config.Config, handlers *handler.Handlers, taskCenter *handler.TaskCenterHandler, runtimeHistory *handler.RuntimeHistoryHandler, jwtMiddleware gin.HandlerFunc) {
	admin := r.Group("/api/admin")
	admin.Use(jwtMiddleware, middleware.AdminOnly())

	admin.GET("/tasks", taskCenter.List)
	admin.GET("/runtime-history", runtimeHistory.List)
	admin.GET("/runtime-history/summary", runtimeHistory.Summary)
	admin.GET("/runtime-history/jobs/:id", runtimeHistory.Detail)
	admin.GET("/users", handlers.Admin.ListUsers)
	admin.POST("/users", handlers.Admin.CreateUser)
	admin.PUT("/users/:id", handlers.Admin.UpdateUser)
	admin.POST("/users/:id/disabled", handlers.Admin.SetUserDisabled)
	admin.DELETE("/users/:id", handlers.Admin.DeleteUser)
	admin.PUT("/users/:id/password", handlers.Admin.ResetUserPassword)
	admin.GET("/login-logs", handlers.Admin.ListLoginLogs)
	admin.GET("/audit-logs", handlers.Admin.ListAuditLogs)
	admin.GET("/invite-codes", handlers.Admin.ListInviteCodes)
	admin.POST("/invite-codes", handlers.Admin.CreateInviteCode)
	admin.DELETE("/invite-codes/:id", handlers.Admin.DeleteInviteCode)

	admin.GET("/system", handlers.Admin.SystemInfo)

	admin.GET("/settings/system", handlers.Admin.GetSystemSettings)
	admin.PUT("/settings/system", handlers.Admin.UpdateSystemSettings)
	admin.GET("/strm/config", handlers.Admin.GetSTRMConfig)
	admin.PUT("/strm/config", handlers.Admin.UpdateSTRMConfig)

	admin.POST("/batch/scan", handlers.Admin.BatchScan)
	admin.POST("/batch/scrape", handlers.Admin.BatchScrape)
	admin.GET("/permissions/:userId", handlers.Admin.GetUserPermission)
	admin.PUT("/permissions/:userId", handlers.Admin.UpdateUserPermission)
	admin.GET("/rating/:mediaId", handlers.Admin.GetContentRating)
	admin.PUT("/rating/:mediaId", handlers.Admin.SetContentRating)

	admin.PUT("/media/:mediaId/metadata", handlers.Admin.UpdateMediaMetadata)
	admin.DELETE("/media/:mediaId", handlers.Admin.DeleteMedia)
	admin.GET("/media/:mediaId/strm", handlers.Admin.GetMediaSTRM)
	admin.PUT("/media/:mediaId/strm", handlers.Admin.UpdateMediaSTRM)
	admin.POST("/series/:seriesId/scrape", handlers.Admin.ScrapeSeriesMetadata)
	admin.PUT("/series/:seriesId/metadata", handlers.Admin.UpdateSeriesMetadata)
	admin.DELETE("/series/:seriesId", handlers.Admin.DeleteSeries)
	admin.POST("/series/merge", handlers.Admin.MergeSeries)
	admin.POST("/series/auto-merge", handlers.Admin.AutoMergeSeries)
	admin.GET("/series/merge-candidates", handlers.Admin.MergeCandidates)

	admin.POST("/media/:mediaId/image/upload", handlers.Admin.UploadMediaImage)
	admin.POST("/media/:mediaId/image/url", handlers.Admin.SetMediaImageByURL)
	admin.POST("/series/:seriesId/image/upload", handlers.Admin.UploadSeriesImage)
	admin.POST("/series/:seriesId/image/url", handlers.Admin.SetSeriesImageByURL)
	admin.POST("/series/:seriesId/poster", handlers.Admin.SetSeriesPosterFromMedia)
	admin.GET("/fs/browse", handlers.Admin.BrowseFS)

	admin.GET("/storage/webdav", handlers.Storage.GetWebDAVConfig)
	admin.PUT("/storage/webdav", handlers.Storage.UpdateWebDAVConfig)
	admin.POST("/storage/webdav/test", handlers.Storage.TestWebDAVConnection)
	admin.GET("/storage/webdav/status", handlers.Storage.GetWebDAVStatus)
	admin.POST("/storage/webdav/libraries/register", handlers.Storage.RegisterWebDAVLibrary)
	admin.GET("/storage/status", handlers.Storage.GetStorageStatus)
	admin.GET("/storage/alist", handlers.Storage.GetAlistConfig)
	admin.PUT("/storage/alist", handlers.Storage.UpdateAlistConfig)
	admin.POST("/storage/alist/test", handlers.Storage.TestAlistConnection)
	admin.GET("/storage/s3", handlers.Storage.GetS3Config)
	admin.PUT("/storage/s3", handlers.Storage.UpdateS3Config)
	admin.POST("/storage/s3/test", handlers.Storage.TestS3Connection)
	admin.POST("/system/clear-data", handlers.Admin.ClearAllData)
	admin.POST("/system/cleanup-residuals", handlers.Admin.CleanupResidualData)

	// 全量备份 / 还原
	admin.GET("/backups", handlers.Admin.ListBackups)
	admin.POST("/backups", handlers.Admin.CreateBackup)
	admin.GET("/backups/:name/download", handlers.Admin.DownloadBackup)
	admin.DELETE("/backups/:name", handlers.Admin.DeleteBackup)
	admin.POST("/backups/:name/restore", handlers.Admin.RestoreBackupLocal)
	admin.POST("/backups/restore", handlers.Admin.RestoreBackup)

	admin.GET("/stats/:userId", handlers.Stats.GetUserStatsAdmin)

	admin.GET("/files", handlers.FileManager.ListFiles)
	admin.GET("/files/folders", handlers.FileManager.GetFolderTree)
	admin.GET("/files/by-folder", handlers.FileManager.ListFilesByFolder)
	admin.POST("/files/folders/create", handlers.FileManager.CreateFolder)
	admin.POST("/files/folders/rename", handlers.FileManager.RenameFolder)
	admin.POST("/files/folders/delete", handlers.FileManager.DeleteFolder)
	admin.GET("/files/:id", handlers.FileManager.GetFileDetail)
	admin.POST("/files/import", handlers.FileManager.ImportFile)
	admin.POST("/files/import/batch", handlers.FileManager.BatchImportFiles)
	admin.GET("/files/scan", handlers.FileManager.ScanDirectory)
	admin.PUT("/files/:id", handlers.FileManager.UpdateFile)
	admin.DELETE("/files/:id", handlers.FileManager.DeleteFile)
	admin.POST("/files/batch/delete", handlers.FileManager.BatchDeleteFiles)
	admin.POST("/files/:id/scrape", handlers.FileManager.ScrapeFile)
	admin.POST("/files/batch/scrape", handlers.FileManager.BatchScrapeFiles)
	admin.POST("/files/rename/preview", handlers.FileManager.PreviewRename)
	admin.POST("/files/rename/execute", handlers.FileManager.ExecuteRename)
	admin.GET("/files/rename/templates", handlers.FileManager.GetRenameTemplates)
	admin.GET("/files/stats", handlers.FileManager.GetStats)
	admin.GET("/files/logs", handlers.FileManager.GetOperationLogs)

	admin.POST("/batch/metadata/media", handlers.BatchMetadata.BatchUpdateMedia)
	admin.POST("/batch/metadata/series", handlers.BatchMetadata.BatchUpdateSeries)
	admin.GET("/export/library", handlers.BatchMetadata.ExportLibrary)
	admin.POST("/import/data", handlers.BatchMetadata.ImportFromExportData)

	admin.POST("/media/batch-move", handlers.Library.BatchMoveMedia)

	admin.POST("/collections", handlers.Collection.CreateCollection)
	admin.POST("/collections/auto-match", handlers.Collection.AutoMatch)
	admin.POST("/collections/rematch", handlers.Collection.Rematch)
	admin.POST("/collections/merge-duplicates", handlers.Collection.MergeDuplicates)
	admin.POST("/collections/cleanup-empty", handlers.Collection.CleanupEmpty)
	admin.GET("/collections/duplicate-stats", handlers.Collection.DuplicateStats)
	admin.PUT("/collections/:id", handlers.Collection.UpdateCollection)
	admin.DELETE("/collections/:id", handlers.Collection.DeleteCollection)
	admin.POST("/collections/:id/media", handlers.Collection.AddMedia)
	admin.DELETE("/collections/:id/media/:mediaId", handlers.Collection.RemoveMedia)
}
